server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/taotao
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root

mybatis:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.taotao.pojo
  configuration:
    mapUnderscoreToCamelCase: true